# Generated by Django 3.2.4 on 2021-08-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dislike_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
